#!/usr/bin/env ruby

flag = ARGV[0] || raise
table = []

until flag.empty?
  i = rand(flag.size)
  table << [i, flag[i].ord]
  flag = flag[0, i] + flag[i+1..-1]
end

1.times do
  puts "["
  table.each do |x|
    puts "  #{x},"
  end
  puts "]"
end
