#!/usr/bin/env ruby

require "base64"

flag = ARGV[0] || raise

text = [
  "If you ever need the flag",
  "it is #{flag}",
  "I hope that helps."
]

svg = '<svg xmlns="http://www.w3.org/2000/svg" height="300" width="1000" font-size="16" font-family="monospace">'
bits1 = []
bits2 = []

text.each_with_index do |row, y|
  row.chars.each_with_index do |let, x|
    bits1 << "<text x='#{x*16}' y='#{y*16+16}'>#{let}</text>"
    if y == 1 and x >= 5
      bits2 << "<rect x='#{x*16-2}' y='#{y*16-2+2}' height='20' width='20' rx='6' ry='6' fill='#444' />"
    end
  end
end

svg << [*bits1.shuffle, *bits2.shuffle].join
svg << "</svg>"

b64 = Base64.strict_encode64(svg)

puts <<EOF
<html>
<body>
<img src="data:image/svg+xml;base64,#{b64}">
</body>
</html>
EOF
